[workspace]
members = ["programs/*", "sdk"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
// Update 3 at 2025-10-22 19:48:05
// Update 13 at 2025-10-18 07:12:21
// Update 34 at 2025-10-27 14:56:18
